### PR TITLE
Migration to .Net Core 3.1 + update nuget packages to latest versions

### PR DESCRIPTION
**Pull request by vitrudchenko**
Migration to .NET Core 3.1.

### CODE REVIEW

**Comment by tbureck** [comment]
I just set up a project which I wanted to use Identity Server with Mongo DB in, but this package apparently doesn't work with the latest version of Identity Server. I think this PR would fix it, so I would be very glad to have the package updated with this.

**Comment by diogodamiani** [comment]
Hi @tbureck and @vitrudchenko. 
It's on Dev branch, but it's not working properly. It seems there are some breaking changes on mappings. 
Fell free to try to solve them. I'll give it a try as soon as possible.
Thanks!

**Comment by vitrudchenko** [comment]
> 
> 
> Hi @tbureck and @vitrudchenko.
> It's on Dev branch, but it's not working properly. It seems there are some breaking changes on mappings.
> Fell free to try to solve them. I'll give it a try as soon as possible.
> Thanks!

Hi @diogodamiani,
Could you provide more details - what is wrong, pls!

**Comment by diogodamiani** [comment]
I've opened #29. 
It seems the model changed. I need to check the changes from version 2.3.x to 4.0.x and the new structure of EntityFramework.Storage.

**Pull request merged**
