### PR TITLE
Test users now being stored in Mongo DB

### PR DESCRIPTION
**Pull request by kutlueren**
Test users store has been removed from controller. Instead, I have created a "Users" collection in Mongo and I have created a data access layer for users as well. Server now can check if user exits in persistent store. Please have a look at it.

### CODE REVIEW

**Comment by diogodamiani** [comment]
Hi, Kutlu! 

Sorry about the delay, I was really busy last weeks!
Your PR is a good intention, but deal with users is not the purpose of IS4. 

Maybe your PR could start another library for User Management or something.

I hope you've got my point.

**Comment by kutlueren** [comment]
Hi Diogo,

Thanks for the reply. 

I am not sure I get what you mean. In your branch, you hold the users in memory which doesnt seem to fit most of the applications and it is not secure as well. In our application, we needed to store the users in a persistance layer and that's why I extended the code. But in any case if you are saying that it is not the purpose of this work you have started, I understand that.

Cheers

**Comment by diogodamiani** [comment]
Hi,

I'll try to be more clear. The Host project act just as an example of how to setup and use the MongoDB persistence layer for IS4 and as a test project as well. So, it uses [in-memory users](https://github.com/IdentityServer/IdentityServer4/tree/dev/src/IdentityServer4/Test).
It's the same approach of [IdentityServer4.EntityFramework](https://github.com/IdentityServer/IdentityServer4.EntityFramework).

Cheers

**Comment by kutlueren** [comment]
Allright. Sounds fair enough. 

Have a nice day

**Pull request closed without merging**
